### PR TITLE
Gradle update and fix

### PR DESCRIPTION
**Pull request by IgorGanapolsky**
Update to the latest gradle and api 21 code.  Reformat XML code.  Remove invalid code that didn't compile in the new api.

### CODE REVIEW

**Comment by writtmeyer** [comment]
Thanks, Igor! I had planned to update this sample for some time - but never came round to do so :-)

I have no time right now to dig into your changes, but will have a look at them this weekend.

**Comment by writtmeyer** [comment]
Marged it. Works like a charm. Thanks again!

**Comment by IgorGanapolsky** [comment]
Was setTransitionName correct replacement for setViewName in
RecyclerViewDemoActivity?

**Comment by IgorGanapolsky** [comment]
@writtmeyer @changetip Have some bitcoin on me! 0.001745 BTC

**Comment by changetip** [comment]
Hi @writtmeyer, @IgorGanapolsky sent you a Bitcoin tip worth 0.001745 BTC ($0.41), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/383345)**.

**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Pull request merged**
